import { Post, Event, User, ForumRoom, ForumMessage } from './types';

export const mockPosts: Post[] = [
  {
    id: '1',
    userName: 'Alex Johnson',
    userAvatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    timeAgo: '2 hours ago',
    text: 'Just completed my morning run! 🏃‍♂️ 5 miles in under 40 minutes - a new personal best!',
    image: 'https://images.pexels.com/photos/2803158/pexels-photo-2803158.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    likes: 24,
    comments: 5,
    liked: false,
  },
  {
    id: '2',
    userName: 'Samantha Lee',
    userAvatar: 'https://images.pexels.com/photos/1587009/pexels-photo-1587009.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    timeAgo: '5 hours ago',
    text: 'Hot yoga session was intense today! Anyone else find that hot yoga helps with muscle recovery? #yoga #fitness',
    image: 'https://images.pexels.com/photos/1051838/pexels-photo-1051838.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    likes: 42,
    comments: 12,
    liked: true,
  },
  {
    id: '3',
    userName: 'Marcus Williams',
    userAvatar: 'https://images.pexels.com/photos/1722198/pexels-photo-1722198.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    timeAgo: 'Yesterday',
    text: 'Looking for a cycling buddy on the east side trails this weekend. Anyone interested?',
    likes: 7,
    comments: 3,
    liked: false,
  },
  {
    id: '4',
    userName: 'Emma Davies',
    userAvatar: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    timeAgo: 'Yesterday',
    text: 'First marathon completed! Thank you all for the support and encouragement. Could not have done it without this amazing community! ❤️',
    image: 'https://images.pexels.com/photos/2526878/pexels-photo-2526878.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    likes: 87,
    comments: 32,
    liked: false,
  },
  {
    id: '5',
    userName: 'David Chen',
    userAvatar: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    timeAgo: '2 days ago',
    text: 'New gym equipment arrived today! Time to take my home workouts to the next level.',
    image: 'https://images.pexels.com/photos/4162488/pexels-photo-4162488.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    likes: 35,
    comments: 8,
    liked: false,
  },
];

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Morning Run Club',
    category: 'Running',
    color: '#4F46E5', // indigo
    date: 'Fri, May 20',
    time: '6:30 AM',
    location: 'Central Park, East Entrance',
    description: 'Join us for a refreshing 5k morning run through Central Park. All fitness levels welcome!',
    attendees: 18,
    latitude: 37.78925,
    longitude: -122.4324,
    distance: 2.3,
  },
  {
    id: '2',
    title: 'Yoga in the Park',
    category: 'Yoga',
    color: '#059669', // emerald
    date: 'Sat, May 21',
    time: '9:00 AM',
    location: 'Golden Gate Park',
    description: 'Outdoor yoga session for all levels. Bring your own mat and water.',
    attendees: 24,
    latitude: 37.77525,
    longitude: -122.4256,
    distance: 3.7,
  },
  {
    id: '3',
    title: 'Weekend Cycling Tour',
    category: 'Cycling',
    color: '#F97316', // orange
    date: 'Sun, May 22',
    time: '7:30 AM',
    location: 'Bay Bridge Lookout',
    description: 'A scenic 30-mile cycling route along the bay. Intermediate level recommended.',
    attendees: 12,
    latitude: 37.79925,
    longitude: -122.4454,
    distance: 5.1,
  },
  {
    id: '4',
    title: 'Basketball Pickup Game',
    category: 'Basketball',
    color: '#EF4444', // red
    date: 'Mon, May 23',
    time: '6:00 PM',
    location: 'Downtown Recreation Center',
    description: 'Casual 3v3 or 5v5 games depending on turnout. All skill levels welcome.',
    attendees: 10,
    latitude: 37.77225,
    longitude: -122.4194,
    distance: 1.5,
  },
  {
    id: '5',
    title: 'Swimming Technique Workshop',
    category: 'Swimming',
    color: '#3B82F6', // blue
    date: 'Tue, May 24',
    time: '5:30 PM',
    location: 'City Aquatic Center',
    description: 'Learn proper stroke techniques and improve your swimming efficiency. Intermediate swimmers.',
    attendees: 8,
    latitude: 37.78525,
    longitude: -122.4494,
    distance: 4.2,
  },
];

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Alex Johnson',
    avatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    distance: 2.3,
    interests: ['Running', 'Cycling', 'Hiking'],
    about: 'Marathon runner and cycling enthusiast. Looking for training partners for my next marathon!',
    connected: false,
  },
  {
    id: '2',
    name: 'Samantha Lee',
    avatar: 'https://images.pexels.com/photos/1587009/pexels-photo-1587009.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    distance: 3.7,
    interests: ['Yoga', 'Pilates', 'Meditation'],
    about: 'Certified yoga instructor passionate about mindfulness and holistic wellness.',
    connected: true,
  },
  {
    id: '3',
    name: 'Marcus Williams',
    avatar: 'https://images.pexels.com/photos/1722198/pexels-photo-1722198.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    distance: 1.5,
    interests: ['Cycling', 'Swimming', 'Triathlon'],
    about: 'Training for my first Ironman competition. Looking for training partners and tips!',
    connected: false,
  },
  {
    id: '4',
    name: 'Emma Davies',
    avatar: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    distance: 4.2,
    interests: ['Running', 'Marathon', 'Trail Running'],
    about: 'Avid trail runner who loves challenging terrain. Always up for discovering new routes!',
    connected: false,
  },
  {
    id: '5',
    name: 'David Chen',
    avatar: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    distance: 5.1,
    interests: ['Gym', 'Weightlifting', 'CrossFit'],
    about: 'Personal trainer specializing in strength training. Happy to share tips and routines!',
    connected: false,
  },
  {
    id: '6',
    name: 'Olivia Martinez',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    distance: 3.3,
    interests: ['Tennis', 'Badminton', 'Squash'],
    about: 'Former college tennis player looking for regular hitting partners. All skill levels welcome!',
    connected: true,
  },
];

export const mockForumRooms: ForumRoom[] = [
  {
    id: 'room-1',
    name: 'Running',
    memberCount: 158,
  },
  {
    id: 'room-2',
    name: 'Cycling',
    memberCount: 92,
  },
  {
    id: 'room-3',
    name: 'Yoga',
    memberCount: 76,
  },
  {
    id: 'room-4',
    name: 'Swimming',
    memberCount: 45,
  },
  {
    id: 'room-5',
    name: 'Fitness General',
    memberCount: 214,
  },
];

export const mockForumMessages: ForumMessage[] = [
  {
    id: 'msg-1',
    roomId: 'room-1',
    userId: 'user-1',
    userName: 'Alex Johnson',
    userAvatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    text: 'Has anyone tried the new Nike ZoomX Vaporfly? Worth the investment?',
    timestamp: '2023-05-15T14:30:00Z',
    isCurrentUser: false,
  },
  {
    id: 'msg-2',
    roomId: 'room-1',
    userId: 'user-2',
    userName: 'Emma Davies',
    userAvatar: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    text: 'I\'ve been using them for about 3 months now. Definitely noticed a difference in my times for longer runs.',
    timestamp: '2023-05-15T14:35:00Z',
    isCurrentUser: false,
  },
  {
    id: 'msg-3',
    roomId: 'room-1',
    userId: 'current-user',
    userName: 'You',
    userAvatar: 'https://images.pexels.com/photos/1722198/pexels-photo-1722198.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    text: 'They\'re quite expensive though. Any alternatives that are somewhat comparable but more affordable?',
    timestamp: '2023-05-15T14:38:00Z',
    isCurrentUser: true,
  },
  {
    id: 'msg-4',
    roomId: 'room-1',
    userId: 'user-3',
    userName: 'Marcus Williams',
    userAvatar: 'https://images.pexels.com/photos/1722198/pexels-photo-1722198.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    text: 'I\'ve had good experience with the Saucony Endorphin Pro. Not quite the same but very good and usually on sale.',
    timestamp: '2023-05-15T14:42:00Z',
    isCurrentUser: false,
  },
  {
    id: 'msg-5',
    roomId: 'room-2',
    userId: 'user-3',
    userName: 'Marcus Williams',
    userAvatar: 'https://images.pexels.com/photos/1722198/pexels-photo-1722198.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    text: 'Anyone riding the coastal route this Saturday? Weather forecast looks great!',
    timestamp: '2023-05-16T09:10:00Z',
    isCurrentUser: false,
  },
  {
    id: 'msg-6',
    roomId: 'room-2',
    userId: 'user-5',
    userName: 'David Chen',
    userAvatar: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    text: 'I\'m in! What time are you planning to start?',
    timestamp: '2023-05-16T09:15:00Z',
    isCurrentUser: false,
  },
  {
    id: 'msg-7',
    roomId: 'room-3',
    userId: 'user-2',
    userName: 'Samantha Lee',
    userAvatar: 'https://images.pexels.com/photos/1587009/pexels-photo-1587009.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    text: 'Just wanted to share this great YouTube channel for at-home yoga practice: YogaWithAdriene. Her 30-day challenges are amazing!',
    timestamp: '2023-05-17T18:05:00Z',
    isCurrentUser: false,
  },
];